### PR TITLE
Add save format checking

### LINKED ISSUE #103: Save compatibility
There is no compatibility for saves between miltiplayer and master. Perhaps we should add some, or at least a converter.

### PR DESCRIPTION
**Pull request by grit96**
Adds a format field to meta.json to make sure the save is compatible with the version of the game.
Fixes #103

### CODE REVIEW

**Comment by grit96** [comment]
Doesn't work properly because it updates the meta file with the defaults each time, and includes the error parameter.

**Comment by olls** [comment]
So it only has problems with old saves which have been created before this code was added?

**Comment by grit96** [comment]
In terms of the format field, yes. But the error field is also saved to
file.

**Comment by olls** [comment]
Oh, I think we need a different way of sending the error through then.

**Comment by grit96** [comment]
Yes

**Pull request closed without merging**
